// Generated by ggen sync --rule breed-dispatch
// Source: schema/cognition-breeds.ttl via sparql/breeds.rq
// Do not edit manually — run: ggen sync

use crate::breeds::asp::Asp;
use crate::breeds::bayesian_network::BayesianNetwork;
use crate::breeds::cbr::Cbr;
use crate::breeds::frame::Eliza;
use crate::breeds::frames_inheritance::FramesInheritance;
use crate::breeds::ltl_monitor::LtlMonitor;
use crate::breeds::meta_reasoning::MetaReasoning;
use crate::breeds::pomdp::Pomdp;
use crate::breeds::production_rules::Mycin;

use wasm4pm_compat::{BreedInput, CognitiveBreed};

pub fn dispatch(breed: &str, input: &BreedInput) -> Option<serde_json::Value> {
    match breed {
        "asp"                 => run_breed(&Asp, input),
        "bayesian_network"    => run_breed(&BayesianNetwork, input),
        "cbr"                 => run_breed(&Cbr, input),
        "eliza"               => run_breed(&Eliza, input),
        "frames_inheritance"  => run_breed(&FramesInheritance, input),
        "ltl_monitor"         => run_breed(&LtlMonitor, input),
        "meta_reasoning"      => run_breed(&MetaReasoning, input),
        "mycin"               => run_breed(&Mycin, input),
        "pomdp"               => run_breed(&Pomdp, input),
        _                     => None,
    }
}

fn run_breed<B: CognitiveBreed>(breed: &B, input: &BreedInput) -> Option<serde_json::Value> {
    breed.run(input)
}
