// @generated by ggen from packs/lsp-max-runtime-pack/ontology.ttl.
// Edit the graph or template, then run `ggen sync run`.

use std::fs;
use std::path::Path;

const REQUIRED_REFUSALS: &[(&str, &str)] = &[
    ("LAW-001", "LSPMAX_UNRECEIPTED_ACTUATION_REFUSED"),
    ("LAW-002", "LSPMAX_DIRECT_ACTUATION_REFUSED"),
    ("LAW-003", "LSPMAX_GENERATED_DRIFT_REFUSED"),
    ("LAW-004", "LSPMAX_HAND_EDITED_GENERATED_OUTPUT"),
    ("LAW-005", "LSPMAX_STANDING_OVERCLAIM_REFUSED"),
    ("LAW-006", "LSPMAX_BASE_SHA_UNRESOLVED"),
    ("LAW-007", "LSPMAX_PRIVATE_SEMANTIC_AUTHORITY_REFUSED"),
    ("LAW-008", "LSPMAX_HOOK_ACTUATION_REFUSED"),
];

const GALL_CHECKPOINTS: &[(&str, usize)] = &[
    ("GALL-001", 1),
    ("GALL-002", 2),
    ("GALL-003", 3),
    ("GALL-004", 4),
    ("GALL-005", 5),
    ("GALL-006", 6),
    ("GALL-007", 7),
    ("GALL-008", 8),
    ("GALL-009", 9),
    ("GALL-010", 10),
];

#[test]
fn ggen_owned_surfaces_exist() {
    for path in [
        "ggen.toml",
        "packs/lsp-max-runtime-pack/pack.toml",
        "packs/lsp-max-runtime-pack/ontology.ttl",
        "docs/generated/GGEN_MANUFACTURING_CONTRACT.md",
        "docs/generated/STANDING_MODEL.md",
        "docs/generated/GALL_ROADMAP.md",
        "evidence/generated/verification-manifest.json",
        ".github/workflows/ggen-contract.yml",
    ] {
        assert!(Path::new(path).is_file(), "missing ggen-owned surface: {path}");
    }
}

#[test]
fn refusal_tokens_are_unique_and_present_in_the_graph() {
    let ontology = fs::read_to_string("packs/lsp-max-runtime-pack/ontology.ttl")
        .expect("read canonical lsp-max ontology");
    let mut tokens = REQUIRED_REFUSALS.iter().map(|(_, token)| *token).collect::<Vec<_>>();
    tokens.sort_unstable();
    tokens.dedup();
    assert_eq!(tokens.len(), REQUIRED_REFUSALS.len(), "duplicate refusal token");
    for (law, token) in REQUIRED_REFUSALS {
        assert!(ontology.contains(law), "missing law {law}");
        assert!(ontology.contains(token), "missing refusal token {token}");
    }
}

#[test]
fn gall_checkpoint_order_is_total_and_crown_is_last() {
    for (index, (id, order)) in GALL_CHECKPOINTS.iter().enumerate() {
        assert_eq!(*order, index + 1, "non-total Gall order at {id}");
    }
    assert_eq!(GALL_CHECKPOINTS.last(), Some(&("GALL-010", 10)));
}

#[test]
fn generated_contract_preserves_zero_unreceipted_actuation() {
    let contract = fs::read_to_string("docs/generated/GGEN_MANUFACTURING_CONTRACT.md")
        .expect("read generated manufacturing contract");
    assert!(contract.contains("Zero unreceipted actuation"));
    assert!(contract.contains("BRCE is the exclusive lawful DO path"));
    assert!(contract.contains("receipt → replay"));
}
