//! GgenLspBackend — CANDIDATE
//! This file would be AUTO-GENERATED by ggen from templates/lsp-max/backend.rs.tera
//! Source: schema/domain.ttl | Run `lsp-max ggen sync` to regenerate

use lsp_max::lsp_types_max::*;

pub struct GgenLspBackend {
    client: lsp_max::Client,
}

impl GgenLspBackend {
    pub fn new(client: lsp_max::Client) -> Self {
        Self { client }
    }
}

#[lsp_max::async_trait]
impl lsp_max::LanguageServer for GgenLspBackend {
    async fn initialize(
        &self,
        _params: InitializeParams,
    ) -> lsp_max::jsonrpc::Result<InitializeResult> {
        Ok(InitializeResult {
            capabilities: crate::capabilities::server_capabilities(),
            ..Default::default()
        })
    }

    async fn initialized(&self, _: InitializedParams) {
        self.client
            .log_message(MessageType::INFO, "ggen-lsp CANDIDATE")
            .await;
    }

    async fn shutdown(&self) -> lsp_max::jsonrpc::Result<()> {
        Ok(())
    }
}
