//! ServerCapabilities — would be AUTO-GENERATED by ggen from capabilities.rs.tera
//! Source: schema/domain.ttl + queries/lsp-max/capabilities.sparql
//! Edit domain.ttl, run `lsp-max ggen sync` — never edit this file directly

use lsp_max::lsp_types_max::*;

pub fn server_capabilities() -> ServerCapabilities {
    ServerCapabilities {
        // CANDIDATE: hover — receipt OPEN
        hover_provider: Some(HoverProviderCapability::Simple(true)),
        // CANDIDATE: completion — receipt OPEN
        completion_provider: Some(CompletionOptions { ..Default::default() }),
        // CANDIDATE: go to definition — receipt OPEN
        definition_provider: Some(OneOf::Left(true)),
        // REFUSED: rename — law:REFUSED in domain.ttl
        // rename_provider: omitted
        // REFUSED: formatting — law:REFUSED in domain.ttl
        // document_formatting_provider: omitted
        ..Default::default()
    }
}
