//! ConformanceVector — would be AUTO-GENERATED by ggen from conformance_vector.rs.tera
//! Source: schema/domain.ttl + queries/lsp-max/conformance.sparql

use lsp_max_protocol::{ConformanceVector, LawAxis};

pub fn conformance_vector() -> ConformanceVector {
    ConformanceVector {
        // OPEN: no methods ADMITTED on any law axis yet
        admitted: vec![],
        // REFUSED axes from domain.ttl law:REFUSED declarations
        refused: vec![
            LawAxis::Custom("textDocument/rename".to_string()),       // law:REFUSED — read-only surface
            LawAxis::Custom("textDocument/formatting".to_string()),   // law:REFUSED — delegated to ggen CLI
        ],
        // CANDIDATE axes: receipt chain OPEN
        unknown: vec![
            LawAxis::Custom("textDocument/hover".to_string()),        // CANDIDATE: receipt OPEN
            LawAxis::Custom("textDocument/completion".to_string()),   // CANDIDATE: receipt OPEN
            LawAxis::Custom("textDocument/definition".to_string()),   // CANDIDATE: receipt OPEN
            LawAxis::Custom("max/ggen-sync".to_string()),             // CANDIDATE: receipt OPEN
        ],
        ..Default::default()
    }
}
