//! ggen-lsp — example LSP generated by ggen + lsp-max pack
//! Status: CANDIDATE — receipt chain OPEN
//! Source of truth: schema/domain.ttl + gen.toml
//! Run `ggen sync` (or `lsp-max ggen sync`) to regenerate from ontology

pub mod backend;
pub mod capabilities;
pub mod conformance;

pub use backend::GgenLspBackend as Backend;
