// Generated by ggen from lsp-max.toml — do not edit manually.
// To update: edit lsp-max.toml and run: ggen sync
// Template: crates/lsp-max-compositor/registry_init.tera

use crate::registry::{ChildServer, ChildTier, ExtensionRouter};

impl ExtensionRouter {
    pub fn new_from_manifest() -> Self {
        let router = Self::new();

        // wasm4pm-lsp (diagnostics-only)
        router.register(
            ".ocel.json",
            ChildServer {
                id: "wasm4pm-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".ocel.json".into(),
                    ".receipt.json".into(),
                    ".ocel.jsonl".into(),
                ],
            },
        );
        router.register(
            ".receipt.json",
            ChildServer {
                id: "wasm4pm-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".ocel.json".into(),
                    ".receipt.json".into(),
                    ".ocel.jsonl".into(),
                ],
            },
        );
        router.register(
            ".ocel.jsonl",
            ChildServer {
                id: "wasm4pm-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".ocel.json".into(),
                    ".receipt.json".into(),
                    ".ocel.jsonl".into(),
                ],
            },
        );
        router.register(
            ".rs",
            ChildServer {
                id: "wasm4pm-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![".rs".into(), ".ts".into(), ".json".into()],
            },
        );
        router.register(
            ".ts",
            ChildServer {
                id: "wasm4pm-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![".rs".into(), ".ts".into(), ".json".into()],
            },
        );
        router.register(
            ".json",
            ChildServer {
                id: "wasm4pm-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![".rs".into(), ".ts".into(), ".json".into()],
            },
        );

        // anti-llm-cheat-lsp (diagnostics-only)
        router.register(
            ".rs",
            ChildServer {
                id: "anti-llm-cheat-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".rs".into(),
                    ".ts".into(),
                    ".tsx".into(),
                    ".json".into(),
                    ".jsonl".into(),
                    ".md".into(),
                ],
            },
        );
        router.register(
            ".ts",
            ChildServer {
                id: "anti-llm-cheat-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".rs".into(),
                    ".ts".into(),
                    ".tsx".into(),
                    ".json".into(),
                    ".jsonl".into(),
                    ".md".into(),
                ],
            },
        );
        router.register(
            ".tsx",
            ChildServer {
                id: "anti-llm-cheat-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".rs".into(),
                    ".ts".into(),
                    ".tsx".into(),
                    ".json".into(),
                    ".jsonl".into(),
                    ".md".into(),
                ],
            },
        );
        router.register(
            ".json",
            ChildServer {
                id: "anti-llm-cheat-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".rs".into(),
                    ".ts".into(),
                    ".tsx".into(),
                    ".json".into(),
                    ".jsonl".into(),
                    ".md".into(),
                ],
            },
        );
        router.register(
            ".jsonl",
            ChildServer {
                id: "anti-llm-cheat-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".rs".into(),
                    ".ts".into(),
                    ".tsx".into(),
                    ".json".into(),
                    ".jsonl".into(),
                    ".md".into(),
                ],
            },
        );
        router.register(
            ".md",
            ChildServer {
                id: "anti-llm-cheat-lsp".into(),
                tier: ChildTier::DiagnosticsOnly,
                extensions: vec![
                    ".rs".into(),
                    ".ts".into(),
                    ".tsx".into(),
                    ".json".into(),
                    ".jsonl".into(),
                    ".md".into(),
                ],
            },
        );

        // ggen-lsp (full)
        router.register(
            ".ttl",
            ChildServer {
                id: "ggen-lsp".into(),
                tier: ChildTier::Primary,
                extensions: vec![".ttl".into(), ".rq".into(), ".tera".into()],
            },
        );
        router.register(
            ".rq",
            ChildServer {
                id: "ggen-lsp".into(),
                tier: ChildTier::Primary,
                extensions: vec![".ttl".into(), ".rq".into(), ".tera".into()],
            },
        );
        router.register(
            ".tera",
            ChildServer {
                id: "ggen-lsp".into(),
                tier: ChildTier::Primary,
                extensions: vec![".ttl".into(), ".rq".into(), ".tera".into()],
            },
        );

        router
    }
}
